"""autogenerated migration

Revision ID: 0f96f1360093
Revises: b29daa5cc061
Create Date: 2025-02-08 15:59:10.017383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f96f1360093'
down_revision: Union[str, None] = 'b29daa5cc061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gh_repo_owner',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=False),
    sa.Column('gravatar_id', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('html_url', sa.String(), nullable=False),
    sa.Column('followers_url', sa.String(), nullable=False),
    sa.Column('following_url', sa.String(), nullable=False),
    sa.Column('gists_url', sa.String(), nullable=False),
    sa.Column('starred_url', sa.String(), nullable=False),
    sa.Column('subscriptions_url', sa.String(), nullable=False),
    sa.Column('organizations_url', sa.String(), nullable=False),
    sa.Column('repos_url', sa.String(), nullable=False),
    sa.Column('events_url', sa.String(), nullable=False),
    sa.Column('received_events_url', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('user_view_type', sa.String(), nullable=False),
    sa.Column('site_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('gh_starred_repo',
    sa.Column('repo_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TEXT(), nullable=False),
    sa.Column('updated_at', sa.TEXT(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.NUMERIC(), nullable=False),
    sa.Column('node_id', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('private', sa.BOOLEAN(), nullable=False),
    sa.Column('html_url', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('fork', sa.BOOLEAN(), nullable=False),
    sa.Column('url', sa.TEXT(), nullable=False),
    sa.Column('forks_url', sa.TEXT(), nullable=False),
    sa.Column('keys_url', sa.TEXT(), nullable=False),
    sa.Column('collaborators_url', sa.TEXT(), nullable=False),
    sa.Column('teams_url', sa.TEXT(), nullable=False),
    sa.Column('hooks_url', sa.TEXT(), nullable=False),
    sa.Column('issue_events_url', sa.TEXT(), nullable=False),
    sa.Column('events_url', sa.TEXT(), nullable=False),
    sa.Column('assignees_url', sa.TEXT(), nullable=False),
    sa.Column('branches_url', sa.TEXT(), nullable=False),
    sa.Column('tags_url', sa.TEXT(), nullable=False),
    sa.Column('blobs_url', sa.TEXT(), nullable=False),
    sa.Column('git_tags_url', sa.TEXT(), nullable=False),
    sa.Column('git_refs_url', sa.TEXT(), nullable=False),
    sa.Column('trees_url', sa.TEXT(), nullable=False),
    sa.Column('statuses_url', sa.TEXT(), nullable=False),
    sa.Column('languages_url', sa.TEXT(), nullable=False),
    sa.Column('stargazers_url', sa.TEXT(), nullable=False),
    sa.Column('contributors_url', sa.TEXT(), nullable=False),
    sa.Column('subscribers_url', sa.TEXT(), nullable=False),
    sa.Column('subscription_url', sa.TEXT(), nullable=False),
    sa.Column('commits_url', sa.TEXT(), nullable=False),
    sa.Column('git_commits_url', sa.TEXT(), nullable=False),
    sa.Column('comments_url', sa.TEXT(), nullable=False),
    sa.Column('issue_comment_url', sa.TEXT(), nullable=False),
    sa.Column('contents_url', sa.TEXT(), nullable=False),
    sa.Column('compare_url', sa.TEXT(), nullable=False),
    sa.Column('merges_url', sa.TEXT(), nullable=False),
    sa.Column('archive_url', sa.TEXT(), nullable=False),
    sa.Column('downloads_url', sa.TEXT(), nullable=False),
    sa.Column('issues_url', sa.TEXT(), nullable=False),
    sa.Column('pulls_url', sa.TEXT(), nullable=False),
    sa.Column('milestones_url', sa.TEXT(), nullable=False),
    sa.Column('notifications_url', sa.TEXT(), nullable=False),
    sa.Column('labels_url', sa.TEXT(), nullable=False),
    sa.Column('releases_url', sa.TEXT(), nullable=False),
    sa.Column('deployments_url', sa.TEXT(), nullable=False),
    sa.Column('pushed_at', sa.TEXT(), nullable=False),
    sa.Column('git_url', sa.TEXT(), nullable=False),
    sa.Column('ssh_url', sa.TEXT(), nullable=False),
    sa.Column('clone_url', sa.TEXT(), nullable=False),
    sa.Column('svn_url', sa.TEXT(), nullable=False),
    sa.Column('homepage', sa.TEXT(), nullable=False),
    sa.Column('size', sa.NUMERIC(), nullable=False),
    sa.Column('stargazers_count', sa.NUMERIC(), nullable=False),
    sa.Column('watchers_count', sa.NUMERIC(), nullable=False),
    sa.Column('language', sa.TEXT(), nullable=False),
    sa.Column('forks_count', sa.NUMERIC(), nullable=False),
    sa.Column('mirror_url', sa.TEXT(), nullable=False),
    sa.Column('open_issues_count', sa.NUMERIC(), nullable=False),
    sa.Column('license', sa.TEXT(), nullable=False),
    sa.Column('topics', sa.JSON().with_variant(sa.Text(), 'sqlite'), nullable=False),
    sa.Column('visibility', sa.TEXT(), nullable=False),
    sa.Column('forks', sa.NUMERIC(), nullable=False),
    sa.Column('open_issues', sa.NUMERIC(), nullable=False),
    sa.Column('watchers', sa.NUMERIC(), nullable=False),
    sa.Column('default_branch', sa.TEXT(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['gh_repo_owner.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('repo_id'),
    sa.UniqueConstraint('node_id', 'name', 'url'),
    sa.UniqueConstraint('repo_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gh_starred_repo')
    op.drop_table('gh_repo_owner')
    # ### end Alembic commands ###
