"""'autogenerated migration'

Revision ID: 1da9c0c76992
Revises: 6d70541bfd90
Create Date: 2025-03-10 12:02:11.287732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1da9c0c76992'
down_revision: Union[str, None] = '6d70541bfd90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gh_starred_repo', sa.Column('created', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('gh_starred_repo', sa.Column('last_updated', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_gh_starred_repo_created'), 'gh_starred_repo', ['created'], unique=False)
    op.create_index(op.f('ix_gh_starred_repo_description'), 'gh_starred_repo', ['description'], unique=False)
    op.create_index(op.f('ix_gh_starred_repo_fork'), 'gh_starred_repo', ['fork'], unique=False)
    op.create_index(op.f('ix_gh_starred_repo_last_updated'), 'gh_starred_repo', ['last_updated'], unique=False)
    op.create_index(op.f('ix_gh_starred_repo_node_id'), 'gh_starred_repo', ['node_id'], unique=False)
    op.create_index(op.f('ix_gh_starred_repo_private'), 'gh_starred_repo', ['private'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gh_starred_repo_private'), table_name='gh_starred_repo')
    op.drop_index(op.f('ix_gh_starred_repo_node_id'), table_name='gh_starred_repo')
    op.drop_index(op.f('ix_gh_starred_repo_last_updated'), table_name='gh_starred_repo')
    op.drop_index(op.f('ix_gh_starred_repo_fork'), table_name='gh_starred_repo')
    op.drop_index(op.f('ix_gh_starred_repo_description'), table_name='gh_starred_repo')
    op.drop_index(op.f('ix_gh_starred_repo_created'), table_name='gh_starred_repo')
    op.drop_column('gh_starred_repo', 'last_updated')
    op.drop_column('gh_starred_repo', 'created')
    # ### end Alembic commands ###
