"""autogenerated migration

Revision ID: 678bf126cb93
Revises: cf5833d1b98d
Create Date: 2025-03-03 02:06:45.151043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '678bf126cb93'
down_revision: Union[str, None] = 'cf5833d1b98d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('login', table_name='gh_repo_owner')
    op.create_index(op.f('ix_gh_repo_owner_login'), 'gh_repo_owner', ['login'], unique=True)
    op.create_index(op.f('ix_gh_repo_owner_type'), 'gh_repo_owner', ['type'], unique=False)
    op.create_index(op.f('ix_gh_repo_owner_url'), 'gh_repo_owner', ['url'], unique=False)
    op.create_index(op.f('ix_gh_starred_repo_archived'), 'gh_starred_repo', ['archived'], unique=False)
    op.create_index(op.f('ix_gh_starred_repo_default_branch'), 'gh_starred_repo', ['default_branch'], unique=False)
    op.create_index(op.f('ix_gh_starred_repo_disabled'), 'gh_starred_repo', ['disabled'], unique=False)
    op.create_index(op.f('ix_gh_starred_repo_forks'), 'gh_starred_repo', ['forks'], unique=False)
    op.create_index(op.f('ix_gh_starred_repo_forks_count'), 'gh_starred_repo', ['forks_count'], unique=False)
    op.create_index(op.f('ix_gh_starred_repo_has_downloads'), 'gh_starred_repo', ['has_downloads'], unique=False)
    op.create_index(op.f('ix_gh_starred_repo_has_issues'), 'gh_starred_repo', ['has_issues'], unique=False)
    op.create_index(op.f('ix_gh_starred_repo_has_pages'), 'gh_starred_repo', ['has_pages'], unique=False)
    op.create_index(op.f('ix_gh_starred_repo_has_wiki'), 'gh_starred_repo', ['has_wiki'], unique=False)
    op.create_index(op.f('ix_gh_starred_repo_is_template'), 'gh_starred_repo', ['is_template'], unique=False)
    op.create_index(op.f('ix_gh_starred_repo_language'), 'gh_starred_repo', ['language'], unique=False)
    op.create_index(op.f('ix_gh_starred_repo_license'), 'gh_starred_repo', ['license'], unique=False)
    op.create_index(op.f('ix_gh_starred_repo_name'), 'gh_starred_repo', ['name'], unique=False)
    op.create_index(op.f('ix_gh_starred_repo_open_issues'), 'gh_starred_repo', ['open_issues'], unique=False)
    op.create_index(op.f('ix_gh_starred_repo_open_issues_count'), 'gh_starred_repo', ['open_issues_count'], unique=False)
    op.create_index(op.f('ix_gh_starred_repo_owner_id'), 'gh_starred_repo', ['owner_id'], unique=False)
    op.create_index(op.f('ix_gh_starred_repo_size'), 'gh_starred_repo', ['size'], unique=False)
    op.create_index(op.f('ix_gh_starred_repo_stargazers_count'), 'gh_starred_repo', ['stargazers_count'], unique=False)
    op.create_index(op.f('ix_gh_starred_repo_topics'), 'gh_starred_repo', ['topics'], unique=False)
    op.create_index(op.f('ix_gh_starred_repo_visibility'), 'gh_starred_repo', ['visibility'], unique=False)
    op.create_index(op.f('ix_gh_starred_repo_watchers'), 'gh_starred_repo', ['watchers'], unique=False)
    op.create_index(op.f('ix_gh_starred_repo_watchers_count'), 'gh_starred_repo', ['watchers_count'], unique=False)
    op.create_index(op.f('ix_gh_stars_api_response_created_at'), 'gh_stars_api_response', ['created_at'], unique=False)
    op.create_index(op.f('ix_gh_stars_api_response_updated_at'), 'gh_stars_api_response', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gh_stars_api_response_updated_at'), table_name='gh_stars_api_response')
    op.drop_index(op.f('ix_gh_stars_api_response_created_at'), table_name='gh_stars_api_response')
    op.drop_index(op.f('ix_gh_starred_repo_watchers_count'), table_name='gh_starred_repo')
    op.drop_index(op.f('ix_gh_starred_repo_watchers'), table_name='gh_starred_repo')
    op.drop_index(op.f('ix_gh_starred_repo_visibility'), table_name='gh_starred_repo')
    op.drop_index(op.f('ix_gh_starred_repo_topics'), table_name='gh_starred_repo')
    op.drop_index(op.f('ix_gh_starred_repo_stargazers_count'), table_name='gh_starred_repo')
    op.drop_index(op.f('ix_gh_starred_repo_size'), table_name='gh_starred_repo')
    op.drop_index(op.f('ix_gh_starred_repo_owner_id'), table_name='gh_starred_repo')
    op.drop_index(op.f('ix_gh_starred_repo_open_issues_count'), table_name='gh_starred_repo')
    op.drop_index(op.f('ix_gh_starred_repo_open_issues'), table_name='gh_starred_repo')
    op.drop_index(op.f('ix_gh_starred_repo_name'), table_name='gh_starred_repo')
    op.drop_index(op.f('ix_gh_starred_repo_license'), table_name='gh_starred_repo')
    op.drop_index(op.f('ix_gh_starred_repo_language'), table_name='gh_starred_repo')
    op.drop_index(op.f('ix_gh_starred_repo_is_template'), table_name='gh_starred_repo')
    op.drop_index(op.f('ix_gh_starred_repo_has_wiki'), table_name='gh_starred_repo')
    op.drop_index(op.f('ix_gh_starred_repo_has_pages'), table_name='gh_starred_repo')
    op.drop_index(op.f('ix_gh_starred_repo_has_issues'), table_name='gh_starred_repo')
    op.drop_index(op.f('ix_gh_starred_repo_has_downloads'), table_name='gh_starred_repo')
    op.drop_index(op.f('ix_gh_starred_repo_forks_count'), table_name='gh_starred_repo')
    op.drop_index(op.f('ix_gh_starred_repo_forks'), table_name='gh_starred_repo')
    op.drop_index(op.f('ix_gh_starred_repo_disabled'), table_name='gh_starred_repo')
    op.drop_index(op.f('ix_gh_starred_repo_default_branch'), table_name='gh_starred_repo')
    op.drop_index(op.f('ix_gh_starred_repo_archived'), table_name='gh_starred_repo')
    op.drop_index(op.f('ix_gh_repo_owner_url'), table_name='gh_repo_owner')
    op.drop_index(op.f('ix_gh_repo_owner_type'), table_name='gh_repo_owner')
    op.drop_index(op.f('ix_gh_repo_owner_login'), table_name='gh_repo_owner')
    op.create_index('login', 'gh_repo_owner', ['login'], unique=True)
    # ### end Alembic commands ###
