"""autogenerated migration

Revision ID: 6bfd78a60985
Revises: 75ba609c9f00
Create Date: 2025-04-30 11:12:05.603015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bfd78a60985'
down_revision: Union[str, None] = '75ba609c9f00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'gh_starred_repo', ['repo_id'])
    op.create_unique_constraint(None, 'gh_stars_api_response', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gh_stars_api_response', type_='unique')
    op.drop_constraint(None, 'gh_starred_repo', type_='unique')
    # ### end Alembic commands ###
