"""autogenerated migration

Revision ID: 75ba609c9f00
Revises: 1da9c0c76992
Create Date: 2025-03-10 23:34:12.747953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75ba609c9f00'
down_revision: Union[str, None] = '1da9c0c76992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('gh_starred_repo', 'created',
    #            existing_type=sa.TIMESTAMP(),
    #            nullable=True,
    #            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # op.alter_column('gh_starred_repo', 'last_updated',
    #            existing_type=sa.TIMESTAMP(),
    #            nullable=True,
    #            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # op.alter_column('gh_stars_api_response', 'created_at',
    #            existing_type=sa.TIMESTAMP(),
    #            nullable=True,
    #            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # op.alter_column('gh_stars_api_response', 'updated_at',
    #            existing_type=sa.TIMESTAMP(),
    #            nullable=True,
    #            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # ### end Alembic commands ###

    # Rename the existing table
    op.rename_table('gh_starred_repo', 'gh_starred_repo_old')

    # Recreate the table with the desired schema
    op.create_table(
        'gh_starred_repo',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('created', sa.TIMESTAMP(), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
        sa.Column('last_updated', sa.TIMESTAMP(), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)'))
    )

    # Copy data from the old table to the new one
    op.execute('INSERT INTO gh_starred_repo (id, created, last_updated) SELECT id, created, last_updated FROM gh_starred_repo_old')

    # Drop the old table
    op.drop_table('gh_starred_repo_old')

    # Repeat the same steps for the gh_stars_api_response table
    op.rename_table('gh_stars_api_response', 'gh_stars_api_response_old')

    op.create_table(
        'gh_stars_api_response',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)')),
        sa.Column('updated_at', sa.TIMESTAMP(), nullable=True, server_default=sa.text('(CURRENT_TIMESTAMP)'))
    )

    op.execute('INSERT INTO gh_stars_api_response (id, created_at, updated_at) SELECT id, created_at, updated_at FROM gh_stars_api_response_old')

    op.drop_table('gh_stars_api_response_old')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('gh_stars_api_response', 'updated_at',
    #            existing_type=sa.TIMESTAMP(),
    #            nullable=False,
    #            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # op.alter_column('gh_stars_api_response', 'created_at',
    #            existing_type=sa.TIMESTAMP(),
    #            nullable=False,
    #            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # op.alter_column('gh_starred_repo', 'last_updated',
    #            existing_type=sa.TIMESTAMP(),
    #            nullable=False,
    #            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # op.alter_column('gh_starred_repo', 'created',
    #            existing_type=sa.TIMESTAMP(),
    #            nullable=False,
    #            existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    # ### end Alembic commands ###
    
    # Rename the current table to keep a backup
    op.rename_table('gh_starred_repo', 'gh_starred_repo_new')

    # Recreate the table with the original schema
    op.create_table(
        'gh_starred_repo',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('created', sa.TIMESTAMP(), nullable=False, server_default=sa.text('(CURRENT_TIMESTAMP)')),
        sa.Column('last_updated', sa.TIMESTAMP(), nullable=False, server_default=sa.text('(CURRENT_TIMESTAMP)'))
    )

    # Copy data back
    op.execute('INSERT INTO gh_starred_repo (id, created, last_updated) SELECT id, created, last_updated FROM gh_starred_repo_new')

    # Drop the temporary table
    op.drop_table('gh_starred_repo_new')

    # Repeat for the gh_stars_api_response table
    op.rename_table('gh_stars_api_response', 'gh_stars_api_response_new')

    op.create_table(
        'gh_stars_api_response',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=False, server_default=sa.text('(CURRENT_TIMESTAMP)')),
        sa.Column('updated_at', sa.TIMESTAMP(), nullable=False, server_default=sa.text('(CURRENT_TIMESTAMP)'))
    )

    op.execute('INSERT INTO gh_stars_api_response (id, created_at, updated_at) SELECT id, created_at, updated_at FROM gh_stars_api_response_new')

    op.drop_table('gh_stars_api_response_new')
