"""autogenerated migration

Revision ID: a8f4644849dc
Revises: 52bfdd9c1281
Create Date: 2025-02-08 16:26:03.459060

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op

import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a8f4644849dc'
down_revision: Union[str, None] = '52bfdd9c1281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gh_starred_repo") as batch_op:
        batch_op.alter_column('license',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gh_starred_repo") as batch_op:
        batch_op.alter_column('license',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
