"""Initial migration

Revision ID: b29daa5cc061
Revises: 
Create Date: 2025-02-08 14:38:50.837931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b29daa5cc061'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def table_exists(table_name):
    # Use sa.text() to create a valid SQL expression for SQLite
    return op.get_bind().execute(sa.text(f"SELECT name FROM sqlite_master WHERE type='table' AND name=:table_name"), {"table_name": table_name}).fetchone() is not None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not table_exists("gh_stars_api_response"):
        op.create_table('gh_stars_api_response',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('json_data', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gh_stars_api_response')
    # ### end Alembic commands ###
