"""initial migration

Revision ID: b9f94767636e
Revises: 
Create Date: 2025-02-08 16:21:29.721878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9f94767636e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Step 1: Create a new table with the desired schema
    op.create_table(
        'gh_repo_owner_new',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('login', sa.VARCHAR(), nullable=False),
        sa.Column('node_id', sa.VARCHAR(), nullable=False),
        sa.Column('avatar_url', sa.VARCHAR(), nullable=True),  # Nullable as intended
        sa.Column('gravatar_id', sa.VARCHAR(), nullable=True),
        sa.Column('url', sa.VARCHAR(), nullable=False),
        sa.Column('html_url', sa.VARCHAR(), nullable=False),
        sa.Column('followers_url', sa.VARCHAR(), nullable=False),
        sa.Column('following_url', sa.VARCHAR(), nullable=False),
        sa.Column('gists_url', sa.VARCHAR(), nullable=False),
        sa.Column('starred_url', sa.VARCHAR(), nullable=False),
        sa.Column('subscriptions_url', sa.VARCHAR(), nullable=False),
        sa.Column('organizations_url', sa.VARCHAR(), nullable=False),
        sa.Column('repos_url', sa.VARCHAR(), nullable=False),
        sa.Column('events_url', sa.VARCHAR(), nullable=False),
        sa.Column('received_events_url', sa.VARCHAR(), nullable=False),
        sa.Column('type', sa.VARCHAR(), nullable=False),
        sa.Column('user_view_type', sa.VARCHAR(), nullable=False),
        sa.Column('site_admin', sa.BOOLEAN(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('login')
    )

    # Step 2: Migrate data from the old table to the new table
    op.execute('INSERT INTO gh_repo_owner_new (id, login, node_id, avatar_url, gravatar_id, url, html_url, followers_url, following_url, gists_url, starred_url, subscriptions_url, organizations_url, repos_url, events_url, received_events_url, type, user_view_type, site_admin) SELECT id, login, node_id, avatar_url, gravatar_id, url, html_url, followers_url, following_url, gists_url, starred_url, subscriptions_url, organizations_url, repos_url, events_url, received_events_url, type, user_view_type, site_admin FROM gh_repo_owner')

    # Step 3: Drop the old table
    op.drop_table('gh_repo_owner')

    # Step 4: Rename the new table to the old table's name
    op.rename_table('gh_repo_owner_new', 'gh_repo_owner')

    # ### end Alembic commands ###


def downgrade() -> None:
    # Reverse the migration steps if necessary
    op.create_table(
        'gh_repo_owner_new',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('login', sa.VARCHAR(), nullable=False),
        sa.Column('node_id', sa.VARCHAR(), nullable=False),
        sa.Column('avatar_url', sa.VARCHAR(), nullable=False),  # Set this to NOT NULL for downgrade
        sa.Column('gravatar_id', sa.VARCHAR(), nullable=True),
        sa.Column('url', sa.VARCHAR(), nullable=False),
        sa.Column('html_url', sa.VARCHAR(), nullable=False),
        sa.Column('followers_url', sa.VARCHAR(), nullable=False),
        sa.Column('following_url', sa.VARCHAR(), nullable=False),
        sa.Column('gists_url', sa.VARCHAR(), nullable=False),
        sa.Column('starred_url', sa.VARCHAR(), nullable=False),
        sa.Column('subscriptions_url', sa.VARCHAR(), nullable=False),
        sa.Column('organizations_url', sa.VARCHAR(), nullable=False),
        sa.Column('repos_url', sa.VARCHAR(), nullable=False),
        sa.Column('events_url', sa.VARCHAR(), nullable=False),
        sa.Column('received_events_url', sa.VARCHAR(), nullable=False),
        sa.Column('type', sa.VARCHAR(), nullable=False),
        sa.Column('user_view_type', sa.VARCHAR(), nullable=False),
        sa.Column('site_admin', sa.BOOLEAN(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('login')
    )

    op.execute('INSERT INTO gh_repo_owner_new (id, login, node_id, avatar_url, gravatar_id, url, html_url, followers_url, following_url, gists_url, starred_url, subscriptions_url, organizations_url, repos_url, events_url, received_events_url, type, user_view_type, site_admin) SELECT id, login, node_id, avatar_url, gravatar_id, url, html_url, followers_url, following_url, gists_url, starred_url, subscriptions_url, organizations_url, repos_url, events_url, received_events_url, type, user_view_type, site_admin FROM gh_repo_owner')

    op.drop_table('gh_repo_owner')
    op.rename_table('gh_repo_owner_new', 'gh_repo_owner')