"""autogenerated migration

Revision ID: e8167c89b646
Revises: 22dcf00a0238
Create Date: 2025-02-08 17:49:46.109645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8167c89b646'
down_revision: Union[str, None] = '22dcf00a0238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gh_repo_owner") as batch_op:
        batch_op.alter_column('site_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    with op.batch_alter_table("gh_starred_repo") as batch_op:
        batch_op.add_column(sa.Column('has_projects', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('has_downloads', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('has_wiki', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('has_pages', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('has_discussions', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('archived', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('disabled', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('allow_forking', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('is_template', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('web_commit_signoff_required', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('private',
                existing_type=sa.BOOLEAN(),
                nullable=True)
        batch_op.alter_column('fork',
                existing_type=sa.BOOLEAN(),
                nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gh_starred_repo") as batch_op:
        batch_op.alter_column('fork',
                existing_type=sa.BOOLEAN(),
                nullable=False)
        batch_op.alter_column('private',
                existing_type=sa.BOOLEAN(),
                nullable=False)
        batch_op.drop_column('web_commit_signoff_required')
        batch_op.drop_column('is_template')
        batch_op.drop_column('allow_forking')
        batch_op.drop_column('disabled')
        batch_op.drop_column('archived')
        batch_op.drop_column('has_discussions')
        batch_op.drop_column('has_pages')
        batch_op.drop_column('has_wiki')
        batch_op.drop_column('has_downloads')
        batch_op.drop_column('has_projects')
    
    with op.batch_alter_table("gh_repo_owner") as batch_op:
        batch_op.alter_column('site_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
