"""autogenerated migration

Revision ID: fb031a734058
Revises: 22dcf00a0238
Create Date: 2025-02-08 17:13:53.057070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb031a734058'
down_revision: Union[str, None] = '22dcf00a0238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gh_starred_repo', sa.Column('has_issues', sa.BOOLEAN(), nullable=False))
    op.add_column('gh_starred_repo', sa.Column('has_projects', sa.BOOLEAN(), nullable=False))
    op.add_column('gh_starred_repo', sa.Column('has_downloads', sa.BOOLEAN(), nullable=False))
    op.add_column('gh_starred_repo', sa.Column('has_wiki', sa.BOOLEAN(), nullable=False))
    op.add_column('gh_starred_repo', sa.Column('has_pages', sa.BOOLEAN(), nullable=False))
    op.add_column('gh_starred_repo', sa.Column('has_discussions', sa.BOOLEAN(), nullable=False))
    op.add_column('gh_starred_repo', sa.Column('archived', sa.BOOLEAN(), nullable=False))
    op.add_column('gh_starred_repo', sa.Column('disabled', sa.BOOLEAN(), nullable=False))
    op.add_column('gh_starred_repo', sa.Column('allow_forking', sa.BOOLEAN(), nullable=False))
    op.add_column('gh_starred_repo', sa.Column('is_template', sa.BOOLEAN(), nullable=False))
    op.add_column('gh_starred_repo', sa.Column('web_commit_signoff_required', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gh_starred_repo', 'web_commit_signoff_required')
    op.drop_column('gh_starred_repo', 'is_template')
    op.drop_column('gh_starred_repo', 'allow_forking')
    op.drop_column('gh_starred_repo', 'disabled')
    op.drop_column('gh_starred_repo', 'archived')
    op.drop_column('gh_starred_repo', 'has_discussions')
    op.drop_column('gh_starred_repo', 'has_pages')
    op.drop_column('gh_starred_repo', 'has_wiki')
    op.drop_column('gh_starred_repo', 'has_downloads')
    op.drop_column('gh_starred_repo', 'has_projects')
    op.drop_column('gh_starred_repo', 'has_issues')
    # ### end Alembic commands ###
