[default]

###########
# GENERAL #
###########

log_level = "INFO"

############
# DATABASE #
############

db_type = "sqlite"
db_drivername = "sqlite+pysqlite"
db_username = ""
db_password = ""
db_host = ""
db_port = ""
db_database = "mygithub.sqlite"

# db_type = "postgres"
# db_drivername = "postgresql+psycopg2"
# db_username = "postgres"
# db_host = "server-ip-or-hostname"
# db_port = "5432"
# db_database = "database-name"

#####################
# FASTAPI & UVICORN #
#####################

fastapi_debug = false
fastapi_title = "MyGithub"
fastapi_summary = "MyGithub project API."
fastapi_description = "Backend API for MyGithub app. https://github.com/redjax/mygithub"
fastapi_version = "0.1.0"
fastapi_openapi_url = "/openapi.json"
fastapi_redirect_slashes = true
fastapi_docs_url = "/docs"
fastapi_redoc_url = "/redoc"
fastapi_openapi_prefix = ""
fastapi_root_path = ""
fastapi_root_path_in_servers = true

## Include custom admin router
fastapi_include_admin_router = false

uvicorn_app = "api.main:fastapi_app"
uvicorn_host = "0.0.0.0"
uvicorn_port = 8000
uvicorn_root_path = "/"
uvicorn_reload = false
uvicorn_log_level = "INFO"

[dev]

###########
# GENERAL #
###########

log_level = "DEBUG"

############
# DATABASE #
############

db_type = "sqlite"
db_drivername = "sqlite+pysqlite"
db_username = ""
db_password = ""
db_host = ""
db_port = ""
db_database = "dev.mygithub.sqlite"

#####################
# FASTAPI & UVICORN #
#####################

fastapi_debug = false
fastapi_title = "MyGithub - Dev"
fastapi_summary = "[Dev] MyGithub project API."
fastapi_description = "[Dev] Backend API for MyGithub app. https://github.com/redjax/mygithub"
fastapi_version = "0.1.0"
fastapi_openapi_url = "/openapi.json"
fastapi_redirect_slashes = true
fastapi_docs_url = "/docs"
fastapi_redoc_url = "/redoc"
fastapi_openapi_prefix = ""
fastapi_root_path = ""
fastapi_root_path_in_servers = true

## Include custom admin router
fastapi_include_admin_router = true

uvicorn_app = "api.main:fastapi_app"
uvicorn_host = "0.0.0.0"
uvicorn_port = 8000
uvicorn_root_path = "/"
uvicorn_reload = true
uvicorn_log_level = "DEBUG"

[prod]

###########
# GENERAL #
###########

############
# DATABASE #
############

#####################
# FASTAPI & UVICORN #
#####################

fastapi_debug = false
fastapi_title = "MyGithub"
fastapi_summary = "MyGithub project API."
fastapi_description = "Backend API for MyGithub app. https://github.com/redjax/mygithub"
fastapi_version = "0.1.0"
fastapi_openapi_url = "/openapi.json"
fastapi_redirect_slashes = true
fastapi_docs_url = "/docs"
fastapi_redoc_url = "/redoc"
fastapi_openapi_prefix = ""
fastapi_root_path = ""
fastapi_root_path_in_servers = true

## Include custom admin router
fastapi_include_admin_router = true

uvicorn_app = "api.main:fastapi_app"
uvicorn_host = "0.0.0.0"
uvicorn_port = 8000
uvicorn_root_path = "/"
uvicorn_reload = false
uvicorn_log_level = "WARNING"
